### ISSUE TITLE
Missing N'Ko language ("ngo"), associated heavily with the RTL "nkoo" script

### ISSUE THREAD

**Issue by brettz9** [shadiabuhilal/rtl-detect#1]
Hi,

Thank you for publishing this project.

I was curious to confirm the source of the scripts, and I see in the source that https://en.wikipedia.org/wiki/Right-to-left is referenced.

In looking at that page now (and confirming at the more extensive  https://en.wikipedia.org/wiki/Script_(Unicode)), I see there is one script item there ("nkoo") which is also right-to-left but is not detected by your code and for which there is a language code which is overwhelmingly* associated with that script, "nqo" (for the N'Ko language).

So your construct at https://github.com/shadiabuhilal/rtl-detect/blob/master/lib/rtl-detect.js#L136-L155 , ought to add a line:

```js
'ngo', /* N'Ko */
```

FWIW, the following languages are "encompassed" languages belonging to a "macrolanguage" which is overwhelmingly expressed with its right-to-left script. None of these have their own "Suppress-Script", so I don't know if that means that is because it is deferring to the macrolanguage (in which case these should be detected as RTL) or because it just happens that not enough information is available on any of them (or they are not predominantly used with just one script). I've asked this at https://stackoverflow.com/questions/47784379/why-are-some-prominent-encompassed-languages-missing-suppress-script as it really seems some of these like Iranian Persian clearly ought to have a "Suppress-Script" (in this case, Arabic) since there are other languages like Bosnian, which have a macrolanguage and their own "Suppress-Script".

I've put the parent macrolanguage in parenthesis for informational purposes:

```
pes (fa)
prs (fa)
ckb (ku)
kmr (ku)
sdh (ku)
pbt (ps)
pbu (ps)
pst (ps)
ydd (yi)
yih (yi)
```

There are also a lot of deprecated codes, some of which, like "iw" corresponding to predominantly RTL languages (in this case "he" Hebrew), that I did not examine.

Finally, there are also a number of scripts (apparently mostly ancient ones) which can be expressed as RTL but for which no language indicates them as being predominantly expressed in that script. Perhaps your script would ideally also detect script directionality, though I know that information is not always available.

I wanted to share and document all of the above, but the only item for which I think it is adequately clear at this time that there is need for a patch is adding "ngo" to your list.

* According to https://tools.ietf.org/html/bcp47#section-3.1.9 , the "Suppress-Script" field of the IANA Language Subtag Registry, "This field indicates a script used to write the overwhelming majority of documents for the given language". The language registry at https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry lists the "Suppress-Script" field for "ngo" as "nkoo", a script which is RTL per https://en.wikipedia.org/wiki/Right-to-left#Current_scripts and https://en.wikipedia.org/wiki/Script_(Unicode).

**Comment by shadiabuhilal** [comment]
@brettz9 
Thanks for your feedback, and I will work on it soon to update the pkg.

**Comment by shadiabuhilal** [comment]
I have added `Avestan` and `N'Ko` languages
https://github.com/shadiabuhilal/rtl-detect/pull/4

**Comment by brettz9** [comment]
It looks though like N'Ko is language code "nqo" per https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry ...

**Comment by brettz9** [comment]
My apologies for supplying the wrong one in the OP...

**Comment by shadiabuhilal** [comment]
Thanks for the feedback, Yes the correct code is `nqo`.
I have just publish the fix.
