### ISSUE TITLE
Hebrew not detected as rtl

### ISSUE THREAD

**Issue by pdehaan** [shadiabuhilal/rtl-detect#11]
```js
const assert = require("assert").strict;
const rtlDetect = require("rtl-detect");
const rtlLangs = require("rtl-detect/lib/rtl-detect")._BIDI_RTL_LANGS;

const debug = rtlLangs.map(lang => {
    const dir = rtlDetect.getLangDir(lang);
    assert.equal(dir, "rtl");
    return {lang, dir};
});
console.log(debug);
```

You can paste that into https://npm.runkit.com/rtl-detect (uses latest v1.0.3, but the code in the repo seems to still be v1.0.2), which shows that Hebrew/Yiddish should be RTL. This seems to be the rtl-detect.js code from the v1.0.3 from npm, which shows that Hebrew and Yiddish are missing:

```js
Object.defineProperty(self, '_BIDI_RTL_LANGS', {
    value: [
        'ae',	/* Avestan */
        'ar',   /* 'العربية', Arabic */
        'arc',  /* Aramaic */
        'bcc',  /* 'بلوچی مکرانی', Southern Balochi */
        'bqi',  /* 'بختياري', Bakthiari */
        'ckb',  /* 'Soranî / کوردی', Sorani */
        'dv',   /* Dhivehi */
        'fa',   /* 'فارسی', Persian */
        'glk',  /* 'گیلکی', Gilaki */
        'ku',   /* 'Kurdî / كوردی', Kurdish */
        'mzn',  /* 'مازِرونی', Mazanderani */
        'nqo',  /* N'Ko */
        'pnb',  /* 'پنجابی', Western Punjabi */
        'ps',   /* 'پښتو', Pashto, */
        'sd',   /* 'سنڌي', Sindhi */
        'ug',   /* 'Uyghurche / ئۇيغۇرچە', Uyghur */
        'ur'    /* 'اردو', Urdu */
    ],
```

Versus v1.0.2 from npm:

https://github.com/shadiabuhilal/rtl-detect/blob/2eed8a33276461a24e7033d1d3a115ee64aee3f5/lib/rtl-detect.js#L136-L157

In fact, it looks like this behavior changed in v1.0.3. If I revert back to v1.0.2, I get the expected 19 `_BIDI_RTL_LANGS` versus the 17 if I use v1.0.3.

---

Looks like this broke about 40 days ago with the latest publish:

```sh
npm info rtl-detect time --json

{
  "modified": "2021-05-10T14:28:48.370Z",
  "created": "2015-02-03T19:49:12.901Z",
  "1.0.0": "2015-02-03T19:49:12.901Z",
  "1.0.1": "2017-12-18T23:19:30.502Z",
  "1.0.2": "2017-12-19T00:20:32.268Z",
  "1.0.3": "2021-05-10T14:28:45.470Z"
}
```

**Comment by orencp** [comment]
Look at the date in which 1.0.3 was released without any reasonable update. 10-May.
It's Jerusalem day. In that day, Israel has started a military operation named "Operation Wall Guardian" after rockets have been launched from Gaza strip to Jerusalem. Shadi Abu Hilal has probably decided to remove the Hebrew and Yidish languages from the RTL languages array.
See Shadi's facebook in order to get familiar with Shadi and his latest post against Israel :
https://www.facebook.com/shadiabuhilal  (I saved a video while going over his posts).
Shadi, please do not involve politics and antisemitism when uploading code to GitHub. Thanks !

**Comment by brettz9** [comment]
I think we should probably be looking to fork this anyways and orient toward becoming a shim/polyfill of https://github.com/tc39/proposal-intl-locale-info because JavaScript is moving to get this functionality built-in.

**Comment by maorseg** [comment]
Thank you orencp for bringing it up,
Shame that people involve politics here as well

**Comment by vheicleRecognition** [comment]
Thank you Oren, good catch.
Such a shame someone is trying to ignore Hebrew out of antisemitism.

**Comment by CallShaul** [comment]
Thank you orencp for shining light upon this inappropriate behavior.

**Comment by OhadAtia** [comment]
Thanks for bringing this up, this is really a shame and wrong. Our craft should be clean of politics.

**Comment by Theblueshield** [comment]
@shadiabuhilal I only have one thing to say to you and I'll tell you politely, fuc* y0u a piece of sh*t. Come to Israel, we are waiting for you. and do not forget one thing, we have some practical knowledge in cyber.
Hope I was polite.

**Comment by brettz9** [comment]
FWIW, per `npm diff --diff=rtl-detect@1.0.3 --diff=rtl-detect@1.0.4` I see that the old behavior re: Hebrew and Yiddish has been restored in a new patch release.
